index: superdupergetchar.o index.o sort.o printphrase.o compare.o
	gcc -o index superdupergetchar.o index.o sort.o printphrase.o compare.o
superdupergetchar.o: superdupergetchar.c all.h
	gcc -c superdupergetchar.c
index.o: index.c all.h
	gcc -c index.c
sort.o:	sort.c all.h
	gcc -c sort.c
printphrase.o: printphrase.c all.h
	gcc -c printphrase.c
compare.o: compare.c all.h
	gcc -c compare.c
